name: demo
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.4.26
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - jiter==0.10.0
      - lazy-loader==0.4
      - lxml==5.4.0
      - networkx==3.4.2
      - numpy==2.2.6
      - openai==1.79.0
      - opencv-python==4.11.0.86
      - openslide-bin==4.0.0.8
      - openslide-python==1.4.2
      - packaging==25.0
      - pillow==11.2.1
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - shapely==2.1.0
      - sniffio==1.3.1
      - tifffile==2025.5.10
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
